const cars = [
    {
        "id": "xc90-recharge",
        "name": "XC90 Recharge",
        "price": 70000,
        "year": "2023-01-01",
        "color": "White",
        "brand": "Volvo",
        "model": "XC90",
        "type": "suv",
        "features": "Plug-in hybrid, spacious interior, advanced safety features",
        "imageUrl": "/assets/images/xc90_recharge.jpg",
        "available": true
    },
    {
        "id": "xc60-recharge",
        "name": "XC60 Recharge",
        "price": 65000,
        "year": "2022-05-01",
        "color": "Black",
        "brand": "Volvo",
        "model": "XC60",
        "type": "suv",
        "features": "Plug-in hybrid, premium sound system, luxury interior",
        "imageUrl": "/assets/images/xc60_recharge.jpg",
        "available": true
    },
    {
        "id": "xc40-recharge",
        "name": "XC40 Recharge",
        "price": 55000,
        "year": "2021-08-01",
        "color": "Silver",
        "brand": "Volvo",
        "model": "XC40",
        "type": "suv",
        "features": "Electric, compact SUV, eco-friendly",
        "imageUrl": "/assets/images/xc40_recharge.jpg",
        "available": true
    },
    {
        "id": "xc40-bev",
        "name": "XC40 Recharge",
        "price": 58000,
        "year": "2021-03-01",
        "color": "Blue",
        "brand": "Volvo",
        "model": "XC40",
        "type": "suv",
        "features": "Pure electric, fast charging, high-tech dashboard",
        "imageUrl": "/assets/images/xc40_bev.jpg",
        "available": true
    },
    {
        "id": "v90-recharge",
        "name": "V90 Recharge",
        "price": 75000,
        "year": "2022-11-01",
        "color": "Grey",
        "brand": "Volvo",
        "model": "V90",
        "type": "estate",
        "features": "Plug-in hybrid, luxurious seats, panoramic sunroof",
        "imageUrl": "/assets/images/v90_recharge.jpg",
        "available": true
    },
    {
        "id": "v60-recharge",
        "name": "V60 Recharge",
        "price": 70000,
        "year": "2022-06-01",
        "color": "Red",
        "brand": "Volvo",
        "model": "V60",
        "type": "estate",
        "features": "Plug-in hybrid, advanced safety, spacious cargo",
        "imageUrl": "/assets/images/v60_recharge.jpg",
        "available": true
    },
    {
        "id": "s90-recharge",
        "name": "S90 Recharge",
        "price": 85000,
        "year": "2023-02-01",
        "color": "Green",
        "brand": "Volvo",
        "model": "S90",
        "type": "sedan",
        "features": "Plug-in hybrid, luxurious interior, smooth driving",
        "imageUrl": "/assets/images/s90_recharge.jpg",
        "available": true
    },
    {
        "id": "s60-recharge",
        "name": "S60 Recharge",
        "price": 70000,
        "year": "2021-09-01",
        "color": "Yellow",
        "brand": "Volvo",
        "model": "S60",
        "type": "sedan",
        "features": "Plug-in hybrid, sleek design, high performance",
        "imageUrl": "/assets/images/s60_recharge.jpg",
        "available": true
    },
    {
        "id": "s60-recharge2",
        "name": "S60 Recharge",
        "price": 70000,
        "year": "2021-09-01",
        "color": "Yellow",
        "brand": "Volvo",
        "model": "S60",
        "type": "sedan",
        "features": "Plug-in hybrid, sleek design, high performance",
        "imageUrl": "/assets/images/s60_recharge.jpg",
        "available": true
    }
];

export default cars;
